name: hello-world
on: push
jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: |
            echo "v-accel ai dynamics"
            echo "welcome to github"
            echo "hello devops"
